sudo: required
dist: precise

#before_install:
#   -  sudo add-apt-repository ppa:beineri/opt-qt551 -y; fi
#  - sudo apt-get update -qq
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libqt5multimedia5

install:
#  - sudo apt-get install -y qt5-default qttools5-dev-tools #install necessary Qt files

script:
  - qmake Music-analyzer.pro #we gonna compile for Unit test first
  - make
  - ./Tests/./tst_tests
