sudo: false
dist: precise

install:
  - sudo apt-get install -y qt5-default qttools5-dev-tools #install necessary Qt files

script:
  - qmake Music-analyzer.pro #we gonna compile for Unit test first
  - make
  - cd Tests
  - ./tst_tests
